export let gameData = [
  {
    name: "地下城与勇士",
    year: "200508",
    pattern: "免费游戏",
    type: "角色扮演",
    manufacturer: "Neople",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  //
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
  {
    name: "穿越火线",
    year: "200705",
    pattern: "免费游戏",
    type: "FPS",
    manufacturer: "Smile Gate",
  },
  {
    name: "英雄联盟",
    year: "200910",
    pattern: "免费游戏",
    type: "MOBA",
    manufacturer: "Riot Games",
  },
]